"""add kata variant of fkey

Revision ID: 40f9a77bdf86
Revises: cd9594601e26
Create Date: 2026-10-06 14:14:43.747674

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "40f9a77bdf86"
down_revision = "cd9594601e26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "kata_variant_of_fkey", "kata", "kata", ["variant_of"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("kata_variant_of_fkey", "kata", type_="foreignkey")
    # ### end Alembic commands ###
