"""initial schema

Revision ID: 917f1f013321
Revises:
Create Date: 2026-10-01 14:15:47.903731

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "917f1f013321"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_katacompletion_kata_id"), "katacompletion", ["kata_id"], unique=False
    )
    op.create_unique_constraint(
        "unique_kata_user", "katacompletion", ["kata_id", "user_id"]
    )
    op.create_foreign_key(None, "katacompletion", "kata", ["kata_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "katacompletion", type_="foreignkey")
    op.drop_constraint("unique_kata_user", "katacompletion", type_="unique")
    op.drop_index(op.f("ix_katacompletion_kata_id"), table_name="katacompletion")
    # ### end Alembic commands ###
