"""initial schema

Revision ID: a0a187c41234
Revises:
Create Date: 2026-10-01 14:48:17.472683

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = "a0a187c41234"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kata",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rank", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("discipline", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("variant_of", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("statement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("signature", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "solution_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("tests", sa.JSON(), nullable=True),
        sa.Column("concepts_used", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kata_discipline"), "kata", ["discipline"], unique=False)
    op.create_index(op.f("ix_kata_rank"), "kata", ["rank"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "disciplineprogression",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("discipline", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "highest_dan_practiced", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "discipline", name="unique_user_discipline"),
    )
    op.create_table(
        "katacompletion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kata_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kata_id"],
            ["kata.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kata_id", "user_id", name="unique_kata_user"),
    )
    op.create_index(
        op.f("ix_katacompletion_kata_id"), "katacompletion", ["kata_id"], unique=False
    )
    op.create_index(
        op.f("ix_katacompletion_user_id"), "katacompletion", ["user_id"], unique=False
    )
    op.create_table(
        "progression",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("core_dan", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("progression")
    op.drop_index(op.f("ix_katacompletion_user_id"), table_name="katacompletion")
    op.drop_index(op.f("ix_katacompletion_kata_id"), table_name="katacompletion")
    op.drop_table("katacompletion")
    op.drop_table("disciplineprogression")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_kata_rank"), table_name="kata")
    op.drop_index(op.f("ix_kata_discipline"), table_name="kata")
    op.drop_table("kata")
    # ### end Alembic commands ###
