"""add code to kata completion

Revision ID: a5aa4427c239
Revises: c188e9eb74be
Create Date: 2026-10-04 16:16:02.684096

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5aa4427c239"
down_revision = "c188e9eb74be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "katacompletion",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("katacompletion", "code")
    # ### end Alembic commands ###
