"""add kata_type and class_name

Revision ID: c188e9eb74be
Revises: a0a187c41234
Create Date: 2026-10-01 18:31:39.692810

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c188e9eb74be"
down_revision = "a0a187c41234"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kata",
        sa.Column(
            "kata_type",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="function",
        ),
    )
    op.add_column(
        "kata",
        sa.Column("class_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kata", "class_name")
    op.drop_column("kata", "kata_type")
    # ### end Alembic commands ###
